###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: http://minsukchang.com/
baseurl: /
author: Minsuk Chang
title: Minsuk Chang
description: Personal Landing Page
avatar: me2.png

# Contacts
email: minsuk@kaist.ac.kr

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
username: minsukchang
twitter: minsuk_chang
linkedin: minsuk
steemit: mswords
facebook: minsuk.chang


# Research Outputs
google_scholar: 1j2nBpoAAAAJ

# Google Analytics
google_analytics: UA-77549813-1
